# Generated by Django 5.0.2 on 2024-03-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_customuser_credit_card_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[('Auther', 'Auther'), ('Sellers', 'Sellers')], max_length=50),
        ),
    ]
