# Generated by Django 5.0.2 on 2024-03-05 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_customuser_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('discription', models.CharField(max_length=500)),
                ('visibility', models.BooleanField(default=True)),
                ('cost', models.IntegerField()),
                ('year_publish', models.IntegerField()),
                ('file', models.FileField(default=None, null=True, upload_to='books/')),
            ],
        ),
    ]
