# Generated by Django 5.0.2 on 2024-03-05 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_books'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='discription',
            new_name='description',
        ),
    ]
