# Generated by Django 5.0.2 on 2024-03-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_alter_customuser_expiry_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='cover_page/'),
        ),
    ]
